#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _alpha_STD_reg(void);
extern void _CaDynamics_E2_reg(void);
extern void _CaDynamics_reg(void);
extern void _Ca_HVA_reg(void);
extern void _Ca_LVA_reg(void);
extern void _Ca_LVAst_reg(void);
extern void _Ca_reg(void);
extern void _Ih_reg(void);
extern void _Im_reg(void);
extern void _Im_v2_reg(void);
extern void _Kd_reg(void);
extern void _K_P_reg(void);
extern void _K_Pst_reg(void);
extern void _K_T_reg(void);
extern void _K_Tst_reg(void);
extern void _Kv2like_reg(void);
extern void _Kv3_1_reg(void);
extern void _Nap_Et2_reg(void);
extern void _Nap_reg(void);
extern void _NaTa_reg(void);
extern void _NaTa_t_reg(void);
extern void _NaTs2_t_reg(void);
extern void _NaTs_reg(void);
extern void _NaV_reg(void);
extern void _ProbAMPANMDA_EMS_reg(void);
extern void _ProbGABAAB_EMS_reg(void);
extern void _SK_E2_reg(void);
extern void _SK_reg(void);
extern void _SKv3_1_reg(void);
extern void _vecevent_reg(void);
extern void _xtra_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," alpha_STD.mod");
    fprintf(stderr," CaDynamics_E2.mod");
    fprintf(stderr," CaDynamics.mod");
    fprintf(stderr," Ca_HVA.mod");
    fprintf(stderr," Ca_LVA.mod");
    fprintf(stderr," Ca_LVAst.mod");
    fprintf(stderr," Ca.mod");
    fprintf(stderr," Ih.mod");
    fprintf(stderr," Im.mod");
    fprintf(stderr," Im_v2.mod");
    fprintf(stderr," Kd.mod");
    fprintf(stderr," K_P.mod");
    fprintf(stderr," K_Pst.mod");
    fprintf(stderr," K_T.mod");
    fprintf(stderr," K_Tst.mod");
    fprintf(stderr," Kv2like.mod");
    fprintf(stderr," Kv3_1.mod");
    fprintf(stderr," Nap_Et2.mod");
    fprintf(stderr," Nap.mod");
    fprintf(stderr," NaTa.mod");
    fprintf(stderr," NaTa_t.mod");
    fprintf(stderr," NaTs2_t.mod");
    fprintf(stderr," NaTs.mod");
    fprintf(stderr," NaV.mod");
    fprintf(stderr," ProbAMPANMDA_EMS.mod");
    fprintf(stderr," ProbGABAAB_EMS.mod");
    fprintf(stderr," SK_E2.mod");
    fprintf(stderr," SK.mod");
    fprintf(stderr," SKv3_1.mod");
    fprintf(stderr," vecevent.mod");
    fprintf(stderr," xtra.mod");
    fprintf(stderr, "\n");
  }
  _alpha_STD_reg();
  _CaDynamics_E2_reg();
  _CaDynamics_reg();
  _Ca_HVA_reg();
  _Ca_LVA_reg();
  _Ca_LVAst_reg();
  _Ca_reg();
  _Ih_reg();
  _Im_reg();
  _Im_v2_reg();
  _Kd_reg();
  _K_P_reg();
  _K_Pst_reg();
  _K_T_reg();
  _K_Tst_reg();
  _Kv2like_reg();
  _Kv3_1_reg();
  _Nap_Et2_reg();
  _Nap_reg();
  _NaTa_reg();
  _NaTa_t_reg();
  _NaTs2_t_reg();
  _NaTs_reg();
  _NaV_reg();
  _ProbAMPANMDA_EMS_reg();
  _ProbGABAAB_EMS_reg();
  _SK_E2_reg();
  _SK_reg();
  _SKv3_1_reg();
  _vecevent_reg();
  _xtra_reg();
}
